import React, { } from 'react';
import { CheckCircle, XCircle, Clock, FileText, PlusCircle, DollarSign, HardDrive, Megaphone, ShieldCheck } from 'lucide-react';

export const mockUsers = { 'applicant@demo.com': { name: 'Dr. Abdullah Al-Salmi', role: 'applicant', email: 'applicant@demo.com', phone: '0501234567', nationalId: '1012345678', dob: '1985-05-20', verified: true }, 'reviewer@demo.com': { name: 'Noura Al-Kathiri', role: 'reviewer', email: 'reviewer@demo.com', phone: '0559876543', nationalId: '2012345678', dob: '1990-11-15', verified: true }, 'editor@demo.com': { name: 'Khalid Al-Saleh', role: 'editor', email: 'editor@demo.com', phone: '0533344455' }, 'admin@demo.com': { name: 'System Admin', role: 'admin', email: 'admin@demo.com', phone: '0511122233' }, };
export const mockApplications = [ { id: 'APP-00124', title: 'Study of Climate Change Impact on Water Resources', status: 'approved', submissionDate: '2024-03-15', stage: 'post-award', applicant: 'King Fahd University of Petroleum and Minerals', totalFunding: 250000, summary: "The project aims to analyze the effects of climate change on water resources in the Eastern Province using advanced hydrological models." }, { id: 'APP-00125', title: '"Our Beaches Without Plastic" Initiative', status: 'revision', submissionDate: '2024-04-01', feedback: 'Please clarify the mechanism for engaging volunteers and the media coverage plan.', stage: 'application', applicant: 'Saudi Environmental Society', totalFunding: 150000, summary: "A community initiative to clean major beaches in the Kingdom and raise awareness about the dangers of plastic pollution." }, { id: 'APP-00126', title: 'Developing Innovative E-Waste Recycling Solutions', status: 'review', submissionDate: '2024-04-20', stage: 'review', applicant: 'Technology Recycling Co.', totalFunding: 400000, summary: "A pioneering project to develop a new chemical process for extracting precious metals from e-waste with high efficiency and low environmental impact." }, { id: 'APP-00127', title: 'Loan Guarantee Program for Small Solar Projects', status: 'approved', submissionDate: '2024-02-10', stage: 'post-award', applicant: 'Clean Technology Group', totalFunding: 750000, summary: "A financial program to facilitate financing for solar energy projects for homes and SMEs." }, { id: 'APP-00128', applicant: 'Sustainability Research Center', title: 'AI-Powered Air Quality Monitoring in Industrial Cities', type: 'Research', submitted: '2024-04-22', status: 'review', smartScore: 88, stage: 'review', totalFunding: 320000, summary: "Using a network of sensors and machine learning models to provide accurate, real-time air quality data in major industrial cities." }, { id: 'APP-00129', applicant: 'Green Horizons Foundation', title: 'Reforestation Project in Asir Region', status: 'rejected', submissionDate: '2024-03-20', stage: 'application', totalFunding: 220000, summary: "A project to plant one million native trees in the Asir region to combat desertification." }, ];
export const mockGrantDetails = { 'APP-00124': { totalFunding: 250000, budget: [ { category: 'Salaries', allocated: 120000 }, { category: 'Equipment', allocated: 80000 }, { category: 'Field Trips', allocated: 30000 }, { category: 'Publishing', allocated: 20000 }, ], expenses: [ { id: 1, date: '2024-04-05', description: 'Water quality sensors', category: 'Equipment', amount: 45000 }, { id: 2, date: '2024-04-10', description: 'Lead researcher salary (April)', category: 'Salaries', amount: 15000 }, ], milestones: [ { id: 1, title: 'Procurement and Installation of Monitoring Devices', status: 'completed', report: 'Q1_Report.pdf', invoice: 'INV-001.pdf', reportSubmitted: true, invoicePaid: true, deadline: '2024-04-30', funds: 125000 }, { id: 2, title: 'Initial Data Collection and Analysis', status: 'active', report: null, invoice: null, reportSubmitted: false, invoicePaid: false, deadline: '2024-07-30', funds: 75000 }, { id: 3, title: 'Writing and Submitting Research Paper', status: 'pending', report: null, invoice: null, reportSubmitted: false, invoicePaid: false, deadline: '2024-09-30', funds: 50000 }, ] }, 'APP-00127': { totalFunding: 750000, budget: [{category: 'Loan Guarantees', allocated: 700000}, {category: 'Admin Fees', allocated: 50000}], expenses: [], milestones: [{id: 1, title: 'Issuance of First Batch of Guarantees', status: 'active', deadline: '2024-06-30', funds: 750000}]} };
export const mockDataRoomFiles = { 'APP-00124': [ { id: 'f1', name: 'Full_Research_Proposal.pdf', type: 'Proposal', uploaded: '2024-03-15' }, { id: 'f2', name: 'Team_CVs.zip', type: 'Team', uploaded: '2024-03-15' }, ], 'APP-00126': [ { id: 'f3', name: 'Feasibility_Study.pdf', type: 'Proposal', uploaded: '2024-04-20' }, { id: 'f4', name: 'Project_Plan.docx', type: 'Plan', uploaded: '2024-04-20' } ] };
export const mockChatHistory = { 'support': [{ from: 'support', text: 'Hello, how can we help you today?', time: '09:30 AM' }], 'APP-00124-team': [ { from: 'Dr. Abdullah', text: 'The first milestone report has been submitted.', time: '10:15 AM' }, { from: 'Fund Team', text: 'Thank you, it will be reviewed shortly.', time: '10:17 AM' }, ], 'general': [{ from: 'Fund Team', text: 'Reminder: Applications for the non-profit support program are now open.', time: 'Yesterday'}] };
export const mockDocumentTemplates = [ { id: 'milestone_report', name: 'Milestone Report', description: 'Used to document progress for a specific grant milestone.'}, { id: 'budget_request', name: 'Budget Modification Request', description: 'Used to request changes to the approved budget line items.' }, { id: 'final_report', name: 'Final Project Report', description: 'Used to provide a comprehensive summary of project outcomes and achievements.'} ];
export const evaluationTemplate = [ { id: 'c1', title: 'Environmental Impact', weight: 30, subCriteria: [ { id: 's1a', text: 'Contribution to carbon emission reduction' }, { id: 's1b', text: 'Contribution to biodiversity' } ] }, { id: 'c2', title: 'Feasibility & Sustainability', weight: 40, subCriteria: [ { id: 's2a', text: 'Realistic timeline and budget' }, { id: 's2b', text: 'Project sustainability plan after funding ends' }, { id: 's2c', text: 'Team experience' } ] }, { id: 'c3', title: 'Innovation & Creativity', weight: 30, subCriteria: [ { id: 's3a', text: 'Use of new technologies or innovative business models' } ] } ];
export const mockReviewAssignments = [ mockApplications.find(a => a.id === 'APP-00126'), mockApplications.find(a => a.id === 'APP-00128'), ];
export const mockIntegrations = [ { id: 'int1', name: 'ELM" for Identity Verification', status: 'active', icon: <HardDrive/>, description: 'To link and automatically verify applicant data.' }, { id: 'int2', name: 'Etimad" Platform for Tenders', status: 'inactive', icon: <HardDrive/>, description: 'To facilitate tendering for funded projects.' }, { id: 'int3', name: 'Nafath" for Identity Verification', status: 'active', icon: <ShieldCheck/>, description: 'To securely verify user identities via the national single sign-on platform.' }, { id: 'int4', name: 'Mali" Financial System', status: 'active', icon: <DollarSign/>, description: 'To manage and track grant payments and financial reporting.' } ];
export let mockNotifications = {
    applicant: [ { id: 1, icon: <CheckCircle className="text-green-500"/>, text: 'Congratulations! Your application "Our Beaches Without Plastic" has been approved.', time: '2 hours ago', unread: true }, { id: 2, icon: <Clock className="text-yellow-500"/>, text: 'Reminder: The Q2 report for grant APP-00124 is due in 1 week.', time: '1 day ago', unread: false}, { id: 5, icon: <XCircle className="text-red-500"/>, text: 'Unfortunately, your application "Reforestation Project in Asir Region" was rejected.', time: '3 days ago', unread: false} ],
    reviewer: [ { id: 3, icon: <FileText className="text-blue-500"/>, text: 'New application "AI-Powered Air Quality Monitoring" assigned for your review.', time: '4 hours ago', unread: true} ],
    admin: [ { id: 4, icon: <PlusCircle className="text-green-500"/>, text: '5 new applications were submitted yesterday.', time: '8 hours ago', unread: true} ],
    editor: []
};

export const sendGlobalAnnouncement = (title, message) => {
    const newAnnouncement = { id: Date.now(), icon: <Megaphone className="text-blue-500"/>, text: `${title}: ${message}`, time: 'Just now', unread: true };
    Object.keys(mockNotifications).forEach(role => {
        mockNotifications[role].unshift(newAnnouncement);
    });
};
